server:
  port: 8080

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    local-cache-scope: statement
    jdbc-type-for-null: null
    use-generated-keys: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
